name: Manual                               # ワークフロー名
on: 
  workflow_dispatch:                       # 手動実行イベント
    inputs:                                # （inputに入力時に起動）
      greeting:                            # 入力パラメーター名
        type: string                       # データ型（boolean/number/string/choice/environment）
        default: Hello                     # 入力パラメーター省略時ののデフォルト値
        required: true                     # 入力パラメーターの必須フラグ
        description: A cheerful word       # 入力パラメータの概要
jobs:                                      # ジョブの定義
  run:                                     # ジョブのID
    runs-on: ubuntu-latest                 # ランナー（Ubuntuで実行）
    steps:                                 # ステップの定義
      - run: echo "${{ inputs.greeting }}" # 入力パラメータ「greeting」の参照
